name: Run Tests
on:
  push:
    branches: [ 'master', '1.9.9' ]  
  pull_request:
    branches: [ 'master', '1.9.9' ]
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1' 
    - name: Restore dependencies       
      run: dotnet restore      
    - name: Run Unit Tests 
      env: 
        source-connection-string: ${{ secrets.SOURCE_CONNECTION_STRING }}        
        destination-connection-string: ${{ secrets.DESTINATION_CONNECTION_STRING }}        
      run: dotnet test     
    - name: Run E2E Tests 
      env: 
        source-connection-string: ${{ secrets.SOURCE_CONNECTION_STRING }}        
        destination-connection-string: ${{ secrets.DESTINATION_CONNECTION_STRING }}            
      run: 
        cd client; dotnet run -- ./configs/e2e-test.config.json
      
